import { Injectable, Logger } from '@nestjs/common';

import { makeExecutableSchema } from '@graphql-tools/schema';
import { GraphQLSchema } from 'graphql';
import { gql } from 'graphql-tag';
import { isDefined } from 'twenty-shared/utils';

import { ScalarsExplorerService } from 'src/engine/api/graphql/services/scalars-explorer.service';
import { WorkspaceGraphqlSchemaSDLService } from 'src/engine/api/graphql/workspace-graphql-schema-sdl/workspace-graphql-schema-sdl.service';
import { workspaceResolverBuilderMethodNames } from 'src/engine/api/graphql/workspace-resolver-builder/factories/factories';
import { WorkspaceResolverFactory } from 'src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory';
import { MetricsService } from 'src/engine/core-modules/metrics/metrics.service';
import { MetricsKeys } from 'src/engine/core-modules/metrics/types/metrics-keys.type';
import { createSlowPathObserver } from 'src/engine/core-modules/observability/utils/slow-path-observer.util';
import { FlatWorkspace } from 'src/engine/core-modules/workspace/types/flat-workspace.type';
import { buildObjectIdByNameMaps } from 'src/engine/metadata-modules/flat-object-metadata/utils/build-object-id-by-name-maps.util';

const SLOW_WORKSPACE_GRAPHQL_SCHEMA_BUILD_MS = 750;

@Injectable()
export class WorkspaceSchemaFactory {
  private readonly logger = new Logger(WorkspaceSchemaFactory.name);

  constructor(
    private readonly scalarsExplorerService: ScalarsExplorerService,
    private readonly workspaceResolverFactory: WorkspaceResolverFactory,
    private readonly workspaceGraphqlSchemaSDLService: WorkspaceGraphqlSchemaSDLService,
    private readonly metricsService: MetricsService,
  ) {}

  async createGraphQLSchema(
    workspace: FlatWorkspace,
    applicationId?: string,
  ): Promise<GraphQLSchema> {
    // OMNIA-CUSTOM: slow-path observer for schema build timing
    const schemaBuildObserver = createSlowPathObserver({
      logger: this.logger,
      message: 'Slow workspace GraphQL schema build',
      thresholdMs: SLOW_WORKSPACE_GRAPHQL_SCHEMA_BUILD_MS,
    });

    const schemaSDLResult = await schemaBuildObserver.observeAsync(
      'schemaSDLMs',
      () =>
        this.workspaceGraphqlSchemaSDLService.getOrComputeSchemaSDL(
          workspace,
          applicationId,
        ),
    );

    if (!isDefined(schemaSDLResult)) {
      return new GraphQLSchema({});
    }

    const {
      sdl,
      usedScalarNames,
      flatObjectMetadataMaps,
      flatFieldMetadataMaps,
    } = schemaSDLResult;

    const { idByNameSingular } = buildObjectIdByNameMaps(
      flatObjectMetadataMaps,
    );

    const autoGeneratedResolvers = await schemaBuildObserver.observeAsync(
      'resolverFactoryMs',
      () =>
        this.workspaceResolverFactory.create(
          flatObjectMetadataMaps,
          flatFieldMetadataMaps,
          idByNameSingular,
          workspaceResolverBuilderMethodNames,
        ),
    );
    const scalarsResolvers =
      this.scalarsExplorerService.getScalarResolvers(usedScalarNames);

    const executableSchema = await schemaBuildObserver.observeAsync(
      'schemaGenerationMs',
      async () =>
        makeExecutableSchema({
          typeDefs: gql`
            ${sdl}
          `,
          resolvers: {
            ...scalarsResolvers,
            ...autoGeneratedResolvers,
          },
        }),
    );

    await this.metricsService.incrementCounter({
      key: MetricsKeys.GraphqlSchemaBuild,
      shouldStoreInCache: false,
    });

    schemaBuildObserver.warnIfSlow();

    return executableSchema;
  }
}
