import {
  defineObject,
  FieldType,
  OnDeleteAction,
  RelationType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
} from 'twenty-sdk/define';

import {
  TELEPHONY_CALL_DIRECTION_OPTIONS,
  TELEPHONY_CALL_SESSION_STATUS_OPTIONS,
} from 'src/constants/field-options';
import {
  AGENT_TELEPHONY_CALL_SESSIONS_FIELD_ID,
  BROKERAGE_AGENT_PROFILE_OBJECT_UNIVERSAL_IDENTIFIER,
  BROKERAGE_CALL_OBJECT_UNIVERSAL_IDENTIFIER,
  BROKERAGE_CALL_TELEPHONY_SESSIONS_FIELD_ID,
  LEAD_TELEPHONY_CALL_SESSIONS_FIELD_ID,
  TAP_CURRENT_CALL_SESSION_FIELD_ID,
  TC_CALL_SESSIONS_FIELD_ID,
  TCL_CALL_SESSIONS_FIELD_ID,
  TCS_AGENT_FIELD_ID,
  TCS_AGENT_PRESENCES_FIELD_ID,
  TCS_ANSWERED_AT_FIELD_ID,
  TCS_BROKERAGE_CALL_FIELD_ID,
  TCS_CAMPAIGN_FIELD_ID,
  TCS_CAMPAIGN_LEAD_FIELD_ID,
  TCS_DIRECTION_FIELD_ID,
  TCS_DISPOSITION_FIELD_ID,
  TCS_DURATION_SECONDS_FIELD_ID,
  TCS_ENDED_AT_FIELD_ID,
  TCS_EVENTS_FIELD_ID,
  TCS_FROM_NUMBER_FIELD_ID,
  TCS_LEAD_FIELD_ID,
  TCS_NAME_FIELD_ID,
  TCS_NOTES_FIELD_ID,
  TCS_PROVIDER_CALL_ID_FIELD_ID,
  TCS_PROVIDER_FIELD_ID,
  TCS_PROVIDER_PARENT_CALL_ID_FIELD_ID,
  TCS_PROVIDER_RECORDING_ID_FIELD_ID,
  TCS_RECORDING_STATUS_FIELD_ID,
  TCS_RECORDING_URL_FIELD_ID,
  TCS_STARTED_AT_FIELD_ID,
  TCS_STATUS_FIELD_ID,
  TCS_TO_NUMBER_FIELD_ID,
  TCE_CALL_SESSION_FIELD_ID,
  TD_CALL_SESSIONS_FIELD_ID,
  TELEPHONY_AGENT_PRESENCE_OBJECT_ID,
  TELEPHONY_CALL_EVENT_OBJECT_ID,
  TELEPHONY_CALL_SESSION_OBJECT_ID,
  TELEPHONY_CAMPAIGN_LEAD_OBJECT_ID,
  TELEPHONY_CAMPAIGN_OBJECT_ID,
  TELEPHONY_DISPOSITION_OBJECT_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: TELEPHONY_CALL_SESSION_OBJECT_ID,
  nameSingular: 'telephonyCallSession',
  namePlural: 'telephonyCallSessions',
  labelSingular: 'Call Session',
  labelPlural: 'Call Sessions',
  description:
    'Live/provider call state linked to campaign routing, lead, agent, and final Brokerage Call.',
  icon: 'IconPhoneCalling',
  labelIdentifierFieldMetadataUniversalIdentifier: TCS_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: TCS_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: TCS_DIRECTION_FIELD_ID,
      type: FieldType.SELECT,
      name: 'direction',
      label: 'Direction',
      icon: 'IconPhone',
      defaultValue: "'OUTBOUND'",
      options: TELEPHONY_CALL_DIRECTION_OPTIONS,
    },
    {
      universalIdentifier: TCS_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconStatusChange',
      defaultValue: "'RESERVED'",
      options: TELEPHONY_CALL_SESSION_STATUS_OPTIONS,
    },
    {
      universalIdentifier: TCS_PROVIDER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'provider',
      label: 'Provider',
      icon: 'IconPlugConnected',
    },
    {
      universalIdentifier: TCS_PROVIDER_CALL_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'providerCallId',
      label: 'Provider Call ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: TCS_PROVIDER_PARENT_CALL_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'providerParentCallId',
      label: 'Provider Parent Call ID',
      icon: 'IconHierarchy',
    },
    {
      universalIdentifier: TCS_PROVIDER_RECORDING_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'providerRecordingId',
      label: 'Provider Recording ID',
      icon: 'IconMicrophone',
    },
    {
      universalIdentifier: TCS_FROM_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'fromNumber',
      label: 'From Number',
      icon: 'IconPhoneOutgoing',
    },
    {
      universalIdentifier: TCS_TO_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'toNumber',
      label: 'To Number',
      icon: 'IconPhoneIncoming',
    },
    {
      universalIdentifier: TCS_STARTED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'startedAt',
      label: 'Started At',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: TCS_ANSWERED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'answeredAt',
      label: 'Answered At',
      icon: 'IconCalendarCheck',
    },
    {
      universalIdentifier: TCS_ENDED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'endedAt',
      label: 'Ended At',
      icon: 'IconCalendarX',
    },
    {
      universalIdentifier: TCS_DURATION_SECONDS_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'durationSeconds',
      label: 'Duration Seconds',
      icon: 'IconClock',
    },
    {
      universalIdentifier: TCS_RECORDING_URL_FIELD_ID,
      type: FieldType.LINKS,
      name: 'recordingUrl',
      label: 'Recording URL',
      icon: 'IconMicrophone',
    },
    {
      universalIdentifier: TCS_RECORDING_STATUS_FIELD_ID,
      type: FieldType.TEXT,
      name: 'recordingStatus',
      label: 'Recording Status',
      icon: 'IconStatusChange',
    },
    {
      universalIdentifier: TCS_NOTES_FIELD_ID,
      type: FieldType.RICH_TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: TCS_CAMPAIGN_LEAD_FIELD_ID,
      type: FieldType.RELATION,
      name: 'campaignLead',
      label: 'Campaign Lead',
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier:
        TELEPHONY_CAMPAIGN_LEAD_OBJECT_ID,
      relationTargetFieldMetadataUniversalIdentifier:
        TCL_CALL_SESSIONS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'campaignLeadId',
      },
    },
    {
      universalIdentifier: TCS_CAMPAIGN_FIELD_ID,
      type: FieldType.RELATION,
      name: 'campaign',
      label: 'Campaign',
      icon: 'IconSpeakerphone',
      relationTargetObjectMetadataUniversalIdentifier:
        TELEPHONY_CAMPAIGN_OBJECT_ID,
      relationTargetFieldMetadataUniversalIdentifier: TC_CALL_SESSIONS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'campaignId',
      },
    },
    {
      universalIdentifier: TCS_AGENT_FIELD_ID,
      type: FieldType.RELATION,
      name: 'agent',
      label: 'Agent',
      icon: 'IconUser',
      relationTargetObjectMetadataUniversalIdentifier:
        BROKERAGE_AGENT_PROFILE_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        AGENT_TELEPHONY_CALL_SESSIONS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'agentId',
      },
    },
    {
      universalIdentifier: TCS_LEAD_FIELD_ID,
      type: FieldType.RELATION,
      name: 'lead',
      label: 'Lead',
      icon: 'IconUser',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        LEAD_TELEPHONY_CALL_SESSIONS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'leadId',
      },
    },
    {
      universalIdentifier: TCS_DISPOSITION_FIELD_ID,
      type: FieldType.RELATION,
      name: 'disposition',
      label: 'Disposition',
      icon: 'IconChecklist',
      relationTargetObjectMetadataUniversalIdentifier:
        TELEPHONY_DISPOSITION_OBJECT_ID,
      relationTargetFieldMetadataUniversalIdentifier: TD_CALL_SESSIONS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'dispositionId',
      },
    },
    {
      universalIdentifier: TCS_BROKERAGE_CALL_FIELD_ID,
      type: FieldType.RELATION,
      name: 'brokerageCall',
      label: 'Brokerage Call',
      icon: 'IconPhoneCall',
      relationTargetObjectMetadataUniversalIdentifier:
        BROKERAGE_CALL_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        BROKERAGE_CALL_TELEPHONY_SESSIONS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'brokerageCallId',
      },
    },
    {
      universalIdentifier: TCS_EVENTS_FIELD_ID,
      type: FieldType.RELATION,
      name: 'events',
      label: 'Events',
      icon: 'IconTimelineEvent',
      relationTargetObjectMetadataUniversalIdentifier:
        TELEPHONY_CALL_EVENT_OBJECT_ID,
      relationTargetFieldMetadataUniversalIdentifier: TCE_CALL_SESSION_FIELD_ID,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier: TCS_AGENT_PRESENCES_FIELD_ID,
      type: FieldType.RELATION,
      name: 'agentPresences',
      label: 'Agent Presences',
      icon: 'IconUserCheck',
      relationTargetObjectMetadataUniversalIdentifier:
        TELEPHONY_AGENT_PRESENCE_OBJECT_ID,
      relationTargetFieldMetadataUniversalIdentifier:
        TAP_CURRENT_CALL_SESSION_FIELD_ID,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
  ],
});
