import {
  defineObject,
  FieldType,
  OnDeleteAction,
  RelationType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
} from 'twenty-sdk/define';

import { POLICY_STATUS_OPTIONS } from 'src/constants/field-options';
import {
  AGENT_POLICIES_FIELD_ID,
  AGENT_PROFILE_OBJECT_UNIVERSAL_IDENTIFIER,
  CARRIER_OBJECT_UNIVERSAL_IDENTIFIER,
  CARRIER_POLICIES_FIELD_ID,
  LEAD_POLICIES_FIELD_ID,
  POLICY_AGENT_FIELD_ID,
  POLICY_APPLICANT_COUNT_FIELD_ID,
  POLICY_APPLICATION_ID_FIELD_ID,
  POLICY_CARRIER_FIELD_ID,
  POLICY_EFFECTIVE_DATE_FIELD_ID,
  POLICY_EXPIRATION_DATE_FIELD_ID,
  POLICY_LEAD_FIELD_ID,
  POLICY_LTV_FIELD_ID,
  POLICY_NAME_FIELD_ID,
  POLICY_OBJECT_UNIVERSAL_IDENTIFIER,
  POLICY_PAID_THROUGH_DATE_FIELD_ID,
  POLICY_POLICY_NUMBER_FIELD_ID,
  POLICY_PREMIUM_FIELD_ID,
  POLICY_PRODUCT_FIELD_ID,
  POLICY_STATUS_FIELD_ID,
  POLICY_SUBMITTED_DATE_FIELD_ID,
  PRODUCT_OBJECT_UNIVERSAL_IDENTIFIER,
  PRODUCT_POLICIES_FIELD_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: POLICY_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'policy',
  namePlural: 'policies',
  labelSingular: 'Policy',
  labelPlural: 'Policies',
  description: 'Insurance policy.',
  icon: 'IconFileText',
  labelIdentifierFieldMetadataUniversalIdentifier: POLICY_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: POLICY_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: POLICY_POLICY_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'policyNumber',
      label: 'Policy Number',
      icon: 'IconHash',
    },
    {
      universalIdentifier: POLICY_APPLICATION_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'applicationId',
      label: 'Application ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: POLICY_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconStatusChange',
      defaultValue: "'SUBMITTED'",
      options: POLICY_STATUS_OPTIONS,
    },
    {
      universalIdentifier: POLICY_PREMIUM_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'premium',
      label: 'Premium',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: POLICY_LTV_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'ltv',
      label: 'LTV',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: POLICY_APPLICANT_COUNT_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'applicantCount',
      label: 'Applicant Count',
      icon: 'IconUsers',
    },
    {
      universalIdentifier: POLICY_SUBMITTED_DATE_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'submittedDate',
      label: 'Submitted Date',
      icon: 'IconCalendarPlus',
    },
    {
      universalIdentifier: POLICY_EFFECTIVE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'effectiveDate',
      label: 'Effective Date',
      icon: 'IconCalendarCheck',
    },
    {
      universalIdentifier: POLICY_EXPIRATION_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'expirationDate',
      label: 'Expiration Date',
      icon: 'IconCalendarX',
    },
    {
      universalIdentifier: POLICY_PAID_THROUGH_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'paidThroughDate',
      label: 'Paid Through Date',
      icon: 'IconCalendarDollar',
    },
    {
      universalIdentifier: POLICY_LEAD_FIELD_ID,
      type: FieldType.RELATION,
      name: 'lead',
      label: 'Lead',
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier: LEAD_POLICIES_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'leadId',
      },
    },
    {
      universalIdentifier: POLICY_CARRIER_FIELD_ID,
      type: FieldType.RELATION,
      name: 'carrier',
      label: 'Carrier',
      icon: 'IconBuildingBank',
      relationTargetObjectMetadataUniversalIdentifier:
        CARRIER_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: CARRIER_POLICIES_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'carrierId',
      },
    },
    {
      universalIdentifier: POLICY_PRODUCT_FIELD_ID,
      type: FieldType.RELATION,
      name: 'product',
      label: 'Product',
      icon: 'IconPackage',
      relationTargetObjectMetadataUniversalIdentifier:
        PRODUCT_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: PRODUCT_POLICIES_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'productId',
      },
    },
    {
      universalIdentifier: POLICY_AGENT_FIELD_ID,
      type: FieldType.RELATION,
      name: 'agent',
      label: 'Agent',
      icon: 'IconUser',
      relationTargetObjectMetadataUniversalIdentifier:
        AGENT_PROFILE_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: AGENT_POLICIES_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'agentId',
      },
    },
  ],
});
