export enum SubscriptionChannel {
  LOGIC_FUNCTION_LOGS_CHANNEL = 'LOGIC_FUNCTION_LOGS_CHANNEL',
  EVENT_STREAM_CHANNEL = 'EVENT_STREAM_CHANNEL',
  AGENT_CHAT_CHANNEL = 'AGENT_CHAT_CHANNEL',
  WORKSPACE_EVENTS_CHANNEL = 'WORKSPACE_EVENTS_CHANNEL',
  EXPORT_JOB_PROGRESS = 'EXPORT_JOB_PROGRESS',
  IMPORT_JOB_PROGRESS = 'IMPORT_JOB_PROGRESS',
}
