import { defineObject, FieldType } from 'twenty-sdk';

import {
  CRM_POLICY_MIRROR_OBJECT_ID,
  CPM_NAME_FIELD_ID,
  CPM_CRM_POLICY_ID_FIELD_ID,
  CPM_POLICY_NUMBER_FIELD_ID,
  CPM_APPLICATION_ID_FIELD_ID,
  CPM_EXTERNAL_POLICY_ID_FIELD_ID,
  CPM_CARRIER_NAME_FIELD_ID,
  CPM_CARRIER_CRM_ID_FIELD_ID,
  CPM_AGENT_NAME_FIELD_ID,
  CPM_AGENT_CRM_ID_FIELD_ID,
  CPM_AGENT_STATUS_FIELD_ID,
  CPM_LEAD_NAME_FIELD_ID,
  CPM_LEAD_CRM_ID_FIELD_ID,
  CPM_EFFECTIVE_DATE_FIELD_ID,
  CPM_EXPIRATION_DATE_FIELD_ID,
  CPM_CRM_STATUS_FIELD_ID,
  CPM_APPLICANT_COUNT_FIELD_ID,
  CPM_LTV_AMOUNT_MICROS_FIELD_ID,
  CPM_LAST_CRM_SYNC_FIELD_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: CRM_POLICY_MIRROR_OBJECT_ID,
  nameSingular: 'payReconCrmPolicyMirror',
  namePlural: 'payReconCrmPolicyMirrors',
  labelSingular: 'CRM Policy Mirror',
  labelPlural: 'CRM Policy Mirrors',
  description: 'Snapshot of CRM policy data for downstream matching',
  icon: 'IconCopy',
  labelIdentifierFieldMetadataUniversalIdentifier: CPM_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: CPM_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Policy display name from CRM',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: CPM_CRM_POLICY_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'crmPolicyId',
      label: 'CRM Policy ID',
      description: 'UUID of Policy record in CRM',
      icon: 'IconId',
    },
    {
      universalIdentifier: CPM_POLICY_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'policyNumber',
      label: 'Policy Number',
      description: 'Policy number from CRM',
      icon: 'IconId',
    },
    {
      universalIdentifier: CPM_APPLICATION_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'applicationId',
      label: 'Application ID',
      description: 'Health Sherpa application ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: CPM_EXTERNAL_POLICY_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'externalPolicyId',
      label: 'External Policy ID',
      description: "Carrier's external policy ID",
      icon: 'IconId',
    },
    {
      universalIdentifier: CPM_CARRIER_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'carrierName',
      label: 'Carrier Name',
      description: 'Denormalized carrier name',
      icon: 'IconBuilding',
    },
    {
      universalIdentifier: CPM_CARRIER_CRM_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'carrierCrmId',
      label: 'Carrier CRM ID',
      description: 'CRM Carrier object ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: CPM_AGENT_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'agentName',
      label: 'Agent Name',
      description: 'Denormalized agent name',
      icon: 'IconUser',
    },
    {
      universalIdentifier: CPM_AGENT_CRM_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'agentCrmId',
      label: 'Agent CRM ID',
      description: 'CRM AgentProfile object ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: CPM_AGENT_STATUS_FIELD_ID,
      type: FieldType.TEXT,
      name: 'agentStatus',
      label: 'Agent Status',
      description: 'Active/termed status of agent',
      icon: 'IconStatusChange',
    },
    {
      universalIdentifier: CPM_LEAD_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'leadName',
      label: 'Lead Name',
      description: 'Denormalized lead/person name',
      icon: 'IconUser',
    },
    {
      universalIdentifier: CPM_LEAD_CRM_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'leadCrmId',
      label: 'Lead CRM ID',
      description: 'CRM Person object ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: CPM_EFFECTIVE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'effectiveDate',
      label: 'Effective Date',
      description: 'CRM-controlled effective date',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: CPM_EXPIRATION_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'expirationDate',
      label: 'Expiration Date',
      description: 'CRM expiration date',
      icon: 'IconCalendarOff',
    },
    {
      universalIdentifier: CPM_CRM_STATUS_FIELD_ID,
      type: FieldType.TEXT,
      name: 'crmStatus',
      label: 'CRM Status',
      description: 'Current CRM policy status',
      icon: 'IconStatusChange',
    },
    {
      universalIdentifier: CPM_APPLICANT_COUNT_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'applicantCount',
      label: 'Applicant Count',
      description: 'Lead + family members (1 = lead only, 2+ = lead + dependents/spouse)',
      icon: 'IconUsers',
    },
    {
      universalIdentifier: CPM_LTV_AMOUNT_MICROS_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'ltvAmountMicros',
      label: 'LTV Amount (micros)',
      description: 'Commission snapshot in micros',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: CPM_LAST_CRM_SYNC_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'lastCrmSync',
      label: 'Last CRM Sync',
      description: 'Last sync timestamp',
      icon: 'IconRefresh',
    },
  ],
});
