import { defineObject, FieldType } from 'twenty-sdk';

import {
  NORMALIZED_BOOK_ROW_OBJECT_ID,
  NBR_NAME_FIELD_ID,
  NBR_ROW_NUMBER_FIELD_ID,
  NBR_CARRIER_POLICY_NUMBER_FIELD_ID,
  NBR_SUBSCRIBER_NUMBER_FIELD_ID,
  NBR_MEMBER_FIRST_NAME_FIELD_ID,
  NBR_MEMBER_LAST_NAME_FIELD_ID,
  NBR_MEMBER_DOB_FIELD_ID,
  NBR_BROKER_NAME_FIELD_ID,
  NBR_BROKER_EFFECTIVE_DATE_FIELD_ID,
  NBR_POLICY_EFFECTIVE_DATE_FIELD_ID,
  NBR_TRUE_EFFECTIVE_DATE_FIELD_ID,
  NBR_PAID_THROUGH_DATE_FIELD_ID,
  NBR_TERM_DATE_FIELD_ID,
  NBR_ELIGIBLE_FOR_COMMISSION_FIELD_ID,
  NBR_NUMBER_OF_MEMBERS_FIELD_ID,
  NBR_PLAN_NAME_FIELD_ID,
  NBR_MONTHLY_PREMIUM_FIELD_ID,
  NBR_MEMBER_RESPONSIBILITY_FIELD_ID,
  NBR_MEMBER_PHONE_FIELD_ID,
  NBR_MEMBER_EMAIL_FIELD_ID,
  NBR_EXCHANGE_SUBSCRIBER_ID_FIELD_ID,
  NBR_BROKER_NPN_FIELD_ID,
  NBR_PAYABLE_AGENT_FIELD_ID,
  NBR_ON_OFF_EXCHANGE_FIELD_ID,
  NBR_COUNTY_FIELD_ID,
  NBR_STATE_FIELD_ID,
  NBR_RAW_PAYLOAD_FIELD_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: NORMALIZED_BOOK_ROW_OBJECT_ID,
  nameSingular: 'payReconNormalizedBookRow',
  namePlural: 'payReconNormalizedBookRows',
  labelSingular: 'Normalized Book Row',
  labelPlural: 'Normalized Book Rows',
  description: 'One normalized row from a parsed carrier BOB file',
  icon: 'IconTable',
  labelIdentifierFieldMetadataUniversalIdentifier: NBR_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: NBR_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Label: "{policyNumber} - row {rowNumber}"',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: NBR_ROW_NUMBER_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'rowNumber',
      label: 'Row Number',
      description: '1-based line number (excluding header)',
      icon: 'IconHash',
    },
    {
      universalIdentifier: NBR_CARRIER_POLICY_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'carrierPolicyNumber',
      label: 'Carrier Policy Number',
      description: "Carrier's policy/member number",
      icon: 'IconId',
    },
    {
      universalIdentifier: NBR_SUBSCRIBER_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'subscriberNumber',
      label: 'Subscriber Number',
      description: 'Subscriber/member ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: NBR_MEMBER_FIRST_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'memberFirstName',
      label: 'Member First Name',
      description: 'Member first name from carrier file',
      icon: 'IconUser',
    },
    {
      universalIdentifier: NBR_MEMBER_LAST_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'memberLastName',
      label: 'Member Last Name',
      description: 'Member last name from carrier file',
      icon: 'IconUser',
    },
    {
      universalIdentifier: NBR_MEMBER_DOB_FIELD_ID,
      type: FieldType.DATE,
      name: 'memberDob',
      label: 'Member DOB',
      description: 'Member date of birth',
      icon: 'IconCake',
    },
    {
      universalIdentifier: NBR_BROKER_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'brokerName',
      label: 'Broker Name',
      description: 'Agent/broker name from carrier file',
      icon: 'IconUser',
    },
    {
      universalIdentifier: NBR_BROKER_EFFECTIVE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'brokerEffectiveDate',
      label: 'Broker Effective Date',
      description: 'Broker effective date from carrier',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: NBR_POLICY_EFFECTIVE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'policyEffectiveDate',
      label: 'Policy Effective Date',
      description: 'Policy effective date from carrier',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: NBR_TRUE_EFFECTIVE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'trueEffectiveDate',
      label: 'True Effective Date',
      description: 'Computed: MAX(broker, policy effective dates)',
      icon: 'IconCalendarEvent',
    },
    {
      universalIdentifier: NBR_PAID_THROUGH_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'paidThroughDate',
      label: 'Paid Through Date',
      description: 'Paid through date from carrier',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: NBR_TERM_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'termDate',
      label: 'Term Date',
      description: 'Policy termination date',
      icon: 'IconCalendarOff',
    },
    {
      universalIdentifier: NBR_ELIGIBLE_FOR_COMMISSION_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'eligibleForCommission',
      label: 'Eligible for Commission',
      description: 'Parsed from Yes/No text in carrier file',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: NBR_NUMBER_OF_MEMBERS_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'numberOfMembers',
      label: 'Number of Members',
      description: 'Member count from carrier',
      icon: 'IconUsers',
    },
    {
      universalIdentifier: NBR_PLAN_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'planName',
      label: 'Plan Name',
      description: 'Plan/product name from carrier',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: NBR_MONTHLY_PREMIUM_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'monthlyPremium',
      label: 'Monthly Premium',
      description: 'Monthly premium amount',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: NBR_MEMBER_RESPONSIBILITY_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'memberResponsibility',
      label: 'Member Responsibility',
      description: "Member's share of premium",
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: NBR_MEMBER_PHONE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'memberPhone',
      label: 'Member Phone',
      description: 'Member phone from carrier',
      icon: 'IconPhone',
    },
    {
      universalIdentifier: NBR_MEMBER_EMAIL_FIELD_ID,
      type: FieldType.TEXT,
      name: 'memberEmail',
      label: 'Member Email',
      description: 'Member email from carrier',
      icon: 'IconMail',
    },
    {
      universalIdentifier: NBR_EXCHANGE_SUBSCRIBER_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'exchangeSubscriberId',
      label: 'Exchange Subscriber ID',
      description: 'FFM Exchange Subscriber ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: NBR_BROKER_NPN_FIELD_ID,
      type: FieldType.TEXT,
      name: 'brokerNpn',
      label: 'Broker NPN',
      description: 'Broker NPN from carrier',
      icon: 'IconId',
    },
    {
      universalIdentifier: NBR_PAYABLE_AGENT_FIELD_ID,
      type: FieldType.TEXT,
      name: 'payableAgent',
      label: 'Payable Agent',
      description: 'Payable agent entity name',
      icon: 'IconUser',
    },
    {
      universalIdentifier: NBR_ON_OFF_EXCHANGE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'onOffExchange',
      label: 'On/Off Exchange',
      description: 'On/Off exchange indicator',
      icon: 'IconToggleLeft',
    },
    {
      universalIdentifier: NBR_COUNTY_FIELD_ID,
      type: FieldType.TEXT,
      name: 'county',
      label: 'County',
      description: 'County',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: NBR_STATE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'state',
      label: 'State',
      description: 'State',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: NBR_RAW_PAYLOAD_FIELD_ID,
      type: FieldType.RAW_JSON,
      name: 'rawPayload',
      label: 'Raw Payload',
      description: 'Complete original row as JSON',
      icon: 'IconBraces',
    },
  ],
});
