import { defineObject, FieldType } from 'twenty-sdk';

import {
  RECONCILIATION_RUN_OBJECT_ID,
  RR_NAME_FIELD_ID,
  RR_TOTAL_BOB_ROWS_FIELD_ID,
  RR_AUTO_MATCHED_FIELD_ID,
  RR_NEEDS_REVIEW_FIELD_ID,
  RR_UNMATCHED_FIELD_ID,
  RR_MISSING_FROM_BOB_FIELD_ID,
  RR_DISCREPANCIES_FOUND_FIELD_ID,
  RR_STATUS_UPDATES_APPLIED_FIELD_ID,
  RR_RUN_STATUS_FIELD_ID,
  RR_MATCHED_AT_FIELD_ID,
  RR_COMPLETED_AT_FIELD_ID,
  RR_STATUS_MATCHING_ID,
  RR_STATUS_MATCHED_ID,
  RR_STATUS_REVIEW_ID,
  RR_STATUS_APPLYING_ID,
  RR_STATUS_COMPLETED_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: RECONCILIATION_RUN_OBJECT_ID,
  nameSingular: 'payReconReconciliationRun',
  namePlural: 'payReconReconciliationRuns',
  labelSingular: 'Reconciliation Run',
  labelPlural: 'Reconciliation Runs',
  description: 'Per-run summary statistics for BOB reconciliation',
  icon: 'IconPlayerPlay',
  labelIdentifierFieldMetadataUniversalIdentifier: RR_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: RR_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'e.g., "Ambetter - 2026-03-10"',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: RR_TOTAL_BOB_ROWS_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'totalBobRows',
      label: 'Total BOB Rows',
      description: 'Total rows from BOB file',
      icon: 'IconHash',
    },
    {
      universalIdentifier: RR_AUTO_MATCHED_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'autoMatched',
      label: 'Auto Matched',
      description: 'Count of auto-matched rows',
      icon: 'IconCheck',
    },
    {
      universalIdentifier: RR_NEEDS_REVIEW_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'needsReview',
      label: 'Needs Review',
      description: 'Count of rows needing review',
      icon: 'IconEye',
    },
    {
      universalIdentifier: RR_UNMATCHED_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'unmatched',
      label: 'Unmatched',
      description: 'Count of unmatched rows',
      icon: 'IconX',
    },
    {
      universalIdentifier: RR_MISSING_FROM_BOB_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'missingFromBob',
      label: 'Missing from BOB',
      description: 'CRM policies not found in BOB',
      icon: 'IconAlertTriangle',
    },
    {
      universalIdentifier: RR_DISCREPANCIES_FOUND_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'discrepanciesFound',
      label: 'Discrepancies Found',
      description: 'Count of status discrepancies',
      icon: 'IconAlertCircle',
    },
    {
      universalIdentifier: RR_STATUS_UPDATES_APPLIED_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'statusUpdatesApplied',
      label: 'Status Updates Applied',
      description: 'Count of write-back updates applied',
      icon: 'IconArrowBack',
    },
    {
      universalIdentifier: RR_RUN_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'runStatus',
      label: 'Run Status',
      description: 'Current status of this reconciliation run',
      icon: 'IconStatusChange',
      defaultValue: "'MATCHING'",
      options: [
        {
          id: RR_STATUS_MATCHING_ID,
          value: 'MATCHING',
          label: 'Matching',
          position: 0,
          color: 'blue',
        },
        {
          id: RR_STATUS_MATCHED_ID,
          value: 'MATCHED',
          label: 'Matched',
          position: 1,
          color: 'turquoise',
        },
        {
          id: RR_STATUS_REVIEW_ID,
          value: 'REVIEW',
          label: 'Review',
          position: 2,
          color: 'orange',
        },
        {
          id: RR_STATUS_APPLYING_ID,
          value: 'APPLYING',
          label: 'Applying',
          position: 3,
          color: 'blue',
        },
        {
          id: RR_STATUS_COMPLETED_ID,
          value: 'COMPLETED',
          label: 'Completed',
          position: 4,
          color: 'green',
        },
      ],
    },
    {
      universalIdentifier: RR_MATCHED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'matchedAt',
      label: 'Matched At',
      description: 'When matching completed',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: RR_COMPLETED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'completedAt',
      label: 'Completed At',
      description: 'When write-back completed',
      icon: 'IconCalendar',
    },
  ],
});
