import { defineObject, FieldType } from 'twenty-sdk';

import {
  STATUS_CHANGE_LOG_OBJECT_ID,
  SCL_NAME_FIELD_ID,
  SCL_CRM_POLICY_ID_FIELD_ID,
  SCL_CRM_POLICY_NUMBER_FIELD_ID,
  SCL_OLD_STATUS_FIELD_ID,
  SCL_NEW_STATUS_FIELD_ID,
  SCL_OLD_EXPIRE_DATE_FIELD_ID,
  SCL_NEW_EXPIRE_DATE_FIELD_ID,
  SCL_SOURCE_FIELD_ID,
  SCL_CARRIER_NAME_FIELD_ID,
  SCL_MATCH_RESULT_ID_FIELD_ID,
  SCL_CONFIDENCE_FIELD_ID,
  SCL_APPLIED_AT_FIELD_ID,
  SCL_REVERTED_FIELD_ID,
  SCL_REVERTED_AT_FIELD_ID,
  SCL_REVERT_REASON_FIELD_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: STATUS_CHANGE_LOG_OBJECT_ID,
  nameSingular: 'payReconStatusChangeLog',
  namePlural: 'payReconStatusChangeLogs',
  labelSingular: 'Status Change Log',
  labelPlural: 'Status Change Logs',
  description: 'Audit trail for CRM policy status changes applied by reconciliation',
  icon: 'IconHistory',
  labelIdentifierFieldMetadataUniversalIdentifier: SCL_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: SCL_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: '"{policyNumber}: {oldStatus} → {newStatus}"',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: SCL_CRM_POLICY_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'crmPolicyId',
      label: 'CRM Policy ID',
      description: 'CRM policy that was updated',
      icon: 'IconId',
    },
    {
      universalIdentifier: SCL_CRM_POLICY_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'crmPolicyNumber',
      label: 'CRM Policy Number',
      description: 'Denormalized for display',
      icon: 'IconId',
    },
    {
      universalIdentifier: SCL_OLD_STATUS_FIELD_ID,
      type: FieldType.TEXT,
      name: 'oldStatus',
      label: 'Old Status',
      description: 'Previous CRM status',
      icon: 'IconStatusChange',
    },
    {
      universalIdentifier: SCL_NEW_STATUS_FIELD_ID,
      type: FieldType.TEXT,
      name: 'newStatus',
      label: 'New Status',
      description: 'New status applied',
      icon: 'IconStatusChange',
    },
    {
      universalIdentifier: SCL_OLD_EXPIRE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'oldExpireDate',
      label: 'Old Expire Date',
      description: 'Previous CRM expiration date',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: SCL_NEW_EXPIRE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'newExpireDate',
      label: 'New Expire Date',
      description: 'New expiration date applied',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: SCL_SOURCE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'source',
      label: 'Source',
      description: 'e.g., "ambetter-bob-2026-03"',
      icon: 'IconFileUpload',
    },
    {
      universalIdentifier: SCL_CARRIER_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'carrierName',
      label: 'Carrier Name',
      description: 'Which carrier BOB triggered this',
      icon: 'IconBuilding',
    },
    {
      universalIdentifier: SCL_MATCH_RESULT_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'matchResultId',
      label: 'Match Result ID',
      description: 'Link to the MatchResult that caused this',
      icon: 'IconLink',
    },
    {
      universalIdentifier: SCL_CONFIDENCE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'confidence',
      label: 'Confidence',
      description: 'Match confidence that led to this change',
      icon: 'IconPercentage',
    },
    {
      universalIdentifier: SCL_APPLIED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'appliedAt',
      label: 'Applied At',
      description: 'When the change was applied',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: SCL_REVERTED_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'reverted',
      label: 'Reverted',
      description: 'Whether this change was reversed',
      icon: 'IconArrowBack',
    },
    {
      universalIdentifier: SCL_REVERTED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'revertedAt',
      label: 'Reverted At',
      description: 'When it was reverted',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: SCL_REVERT_REASON_FIELD_ID,
      type: FieldType.TEXT,
      name: 'revertReason',
      label: 'Revert Reason',
      description: 'Why it was reverted',
      icon: 'IconNote',
    },
  ],
});
