# ElastiCache Redis Addon
# Creates a Redis 7.1 cluster with noeviction policy for BullMQ

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: Your workload's name.

Resources:
  # Security group for Redis
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Twenty CRM ElastiCache Redis
      VpcId:
        Fn::ImportValue: !Sub ${App}-${Env}-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub ${App}-${Env}-EnvironmentSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${App}-${Env}-redis-sg

  # Subnet group for Redis
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub ${App}-${Env}-redis-subnet-group
      Description: Subnet group for Twenty CRM Redis
      SubnetIds:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ','
                - Fn::ImportValue: !Sub ${App}-${Env}-PrivateSubnets
        - Fn::Select:
            - 1
            - Fn::Split:
                - ','
                - Fn::ImportValue: !Sub ${App}-${Env}-PrivateSubnets

  # Parameter group with noeviction policy (required by BullMQ)
  RedisParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis7
      Description: Redis parameters for Twenty CRM with BullMQ
      Properties:
        maxmemory-policy: noeviction

  # Redis cluster
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: !Sub ${App}-${Env}-redis
      Engine: redis
      EngineVersion: '7.1'
      CacheNodeType: cache.t4g.micro
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      CacheParameterGroupName: !Ref RedisParameterGroup
      VpcSecurityGroupIds:
        - !Ref RedisSecurityGroup
      PreferredMaintenanceWindow: 'sun:05:00-sun:06:00'
      SnapshotRetentionLimit: 1
      SnapshotWindow: '04:00-05:00'
      Tags:
        - Key: Name
          Value: !Sub ${App}-${Env}-redis

  # SSM Parameter for Redis URL
  RedisURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /copilot/${App}/${Env}/secrets/REDIS_URL
      Type: SecureString
      Value: !Sub
        - 'redis://${Endpoint}:6379'
        - Endpoint: !GetAtt RedisCluster.RedisEndpoint.Address
      Description: Redis connection URL for Twenty CRM

Outputs:
  RedisEndpoint:
    Description: ElastiCache Redis endpoint
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      Name: !Sub ${App}-${Env}-RedisEndpoint

  RedisPort:
    Description: ElastiCache Redis port
    Value: !GetAtt RedisCluster.RedisEndpoint.Port
    Export:
      Name: !Sub ${App}-${Env}-RedisPort

  RedisSecurityGroupId:
    Description: Security group ID for Redis
    Value: !Ref RedisSecurityGroup
    Export:
      Name: !Sub ${App}-${Env}-RedisSecurityGroup
