# S3 Storage Addon
# Creates an encrypted S3 bucket for file storage with IAM role access

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: Your workload's name.

Resources:
  # S3 bucket for file storage
  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${App}-${Env}-storage-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      Tags:
        - Key: Name
          Value: !Sub ${App}-${Env}-storage

  # IAM policy for S3 access
  StorageBucketAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for ECS tasks to access Twenty CRM S3 bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3BucketAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - !GetAtt StorageBucket.Arn
              - !Sub ${StorageBucket.Arn}/*

Outputs:
  # Copilot auto-injects outputs named with specific suffixes
  # "Name" suffix creates an environment variable
  StorageS3BucketName:
    Description: S3 bucket name for file storage (injected as STORAGE_S3_BUCKET_NAME)
    Value: !Ref StorageBucket

  StorageS3Region:
    Description: S3 bucket region (injected as STORAGE_S3_REGION)
    Value: !Ref AWS::Region

  StorageBucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt StorageBucket.Arn
    Export:
      Name: !Sub ${App}-${Env}-StorageBucketArn

  # Policy ARN that Copilot attaches to the task role
  StorageBucketAccessPolicyArn:
    Description: IAM policy ARN for S3 access
    Value: !Ref StorageBucketAccessPolicy
